### ISSUE TITLE
Samsung Galaxy Note8

### ISSUE THREAD

**Issue by embo2000** [MostafaEisam/android-call-recorder#1]
The incoming voice is not recorded with Samsung Galaxy Note8.  Tried all the different audio sources.

**Comment by embo2000** [comment]
The MediaEncoder options for encoder does not work for either 3gp or aac:

E/MediaRecorder: start failed: -2147483648
E/RecordingService: java.lang.RuntimeException: start failed.
        at android.media.MediaRecorder._start(Native Method)
        at android.media.MediaRecorder.start(MediaRecorder.java:1277)
        at com.github.axet.callrecorder.services.RecordingService$6.run(RecordingService.java:916)
